<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<<<<<<< HEAD
<testsuite name="org.testscript.ConsumeOpenCourseByPublicUserAndCheckCourseStatAsMentor" tests="2" time="1.014" ignored="0" failures="0" timestamp="07 Dec 2018 09:32:40 GMT" skipped="1" hostname="QUALITRIX-PC" errors="1">
  <testcase name="openApplication" time="0.000" classname="org.testscript.ConsumeOpenCourseByPublicUserAndCheckCourseStatAsMentor">
    <error type="org.openqa.selenium.WebDriverException" message="Timed out waiting for driver server to start.
Build info: version: &#039;3.12.0&#039;, revision: &#039;7c6e0b3&#039;, time: &#039;2018-05-08T14:04:26.12Z&#039;
System info: host: &#039;QUALITRIX-PC&#039;, ip: &#039;192.168.137.1&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_151&#039;
Driver info: driver.version: ChromeDriver">
      <![CDATA[org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'QUALITRIX-PC', ip: '192.168.137.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:192)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:178)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at org.startup.BaseTest.openApplication(BaseTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
=======
<testsuite ignored="0" hostname="Qualitrix-LinuxPC" failures="1" tests="1" name="org.testscript.ConsumeOpenCourseByPublicUserAndCheckCourseStatAsMentor" time="7.075" errors="0" timestamp="07 Dec 2018 12:46:58 GMT" skipped="0">
  <testcase classname="org.testscript.ConsumeOpenCourseByPublicUserAndCheckCourseStatAsMentor" name="consumeOpenCourseByPublicUserAndCheckCourseStatAsMentor" time="7.075">
    <failure message="Failed on logging In, Exception : Index 2 out-of-bounds for length 0" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failed on logging In, Exception : Index 2 out-of-bounds for length 0
	at org.testng.Assert.fail(Assert.java:94)
	at org.pageobjects.SignUpPageObj.userLogin(SignUpPageObj.java:166)
	at org.testscript.ConsumeOpenCourseByPublicUserAndCheckCourseStatAsMentor.consumeOpenCourseByPublicUserAndCheckCourseStatAsMentor(ConsumeOpenCourseByPublicUserAndCheckCourseStatAsMentor.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
>>>>>>> fd04c9623bd7c1c59433d937381798497fdf2ad8
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:19670/status] to be available after 20002 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:187)
	... 24 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:148)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 25 more
]]>
    </error>
  </testcase> <!-- openApplication -->
  <testcase name="consumeOpenCourseByPublicUserAndCheckCourseStatAsMentor" time="1.014" classname="org.testscript.ConsumeOpenCourseByPublicUserAndCheckCourseStatAsMentor">
    <skipped/>
  </testcase> <!-- consumeOpenCourseByPublicUserAndCheckCourseStatAsMentor -->
</testsuite> <!-- org.testscript.ConsumeOpenCourseByPublicUserAndCheckCourseStatAsMentor -->
